name: Latest YouTube Videos
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's profile README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path: ./profile/README.md
          comment_tag_name: "YOUTUBE-VIDEOS-LIST"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCkdDcxjml85-Ydn7Dc577WQ"
          commit_message: "Updated with the latest youtube videos"
          committer_username: "Youtubot"
          committer_email: "academy@betterask.erni"
